package mybinanceapi

import "github.com/shopspring/decimal"

type PmMMarginOrderGetReq struct {
	Symbol            *string `json:"symbol"`            //YES	交易对
	OrderId           *int64  `json:"orderId"`           //No	订单ID
	OrigClientOrderId *int64  `json:"origClientOrderId"` //NO  必须发送 orderId 或 origClientOrderId 其中一个
	RecvWindow        *int64  `json:"recvWindow"`
	Timestamp         *int64  `json:"timestamp"`
}

type PmMMarginOrderGetApi struct {
	client *PmMRestClient
	req    *PmMMarginOrderGetReq
}

func (api *PmMMarginOrderGetApi) Symbol(Symbol string) *PmMMarginOrderGetApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginOrderGetApi) OrderId(OrderId int64) *PmMMarginOrderGetApi {
	api.req.OrderId = GetPointer(OrderId)
	return api
}
func (api *PmMMarginOrderGetApi) OrigClientOrderId(OrigClientOrderId int64) *PmMMarginOrderGetApi {
	api.req.OrigClientOrderId = GetPointer(OrigClientOrderId)
	return api
}
func (api *PmMMarginOrderGetApi) RecvWindow(RecvWindow int64) *PmMMarginOrderGetApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOrderGetApi) Timestamp(Timestamp int64) *PmMMarginOrderGetApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOrderPostReq struct {
	Symbol                  *string          `json:"symbol"`                  //YES	交易对
	Side                    *string          `json:"side"`                    //YES	BUY ; SELL
	Type                    *string          `json:"type"`                    //YES	详见枚举定义：订单类型
	Quantity                *decimal.Decimal `json:"quantity"`                //NO
	QuoteOrderQty           *decimal.Decimal `json:"quoteOrderQty"`           //NO
	Price                   *decimal.Decimal `json:"price"`                   //NO
	StopPrice               *decimal.Decimal `json:"stopPrice"`               //NO	与 STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT，和 TAKE_PROFIT_LIMIT 订单一起使用
	NewClientOrderId        *string          `json:"newClientOrderId"`        //NO	客户自定义的唯一订单ID。若未发送自动生成。
	NewOrderRespType        *string          `json:"newOrderRespType"`        //NO	设置响应: JSON。 ACK， RESULT， 或 FULL; MARKET 和 LIMIT 订单类型默认为 FULL， 所有其他订单默认为 ACK
	IcebergQty              *decimal.Decimal `json:"icebergQty"`              //NO	与 LIMIT， STOP_LOSS_LIMIT，和 TAKE_PROFIT_LIMIT 一起使用创建 iceberg 订单
	SideEffectType          *string          `json:"sideEffectType"`          //NO	NO_SIDE_EFFECT， MARGIN_BUY，AUTO_REPAY,AUTO_BORROW_REPAY；默认为 NO_SIDE_EFFECT
	TimeInForce             *string          `json:"timeInForce"`             //NO	GTC，IOC，FOK
	SelfTradePreventionMode *string          `json:"selfTradePreventionMode"` //NO	允许的 ENUM 取决于交易对的配置。支持的值有 EXPIRE_TAKER，EXPIRE_MAKER，EXPIRE_BOTH，NONE
	AutoRepayAtCancel       *bool            `json:"autoRepayAtCancel"`       //NO	Only when MARGIN_BUY or AUTO_BORROW_REPAY order takes effect, true means that the debt generated by the order needs to be repay after the order is cancelled. The default is true
	RecvWindow              *int64           `json:"recvWindow"`              //NO	赋值不能超过 60000
	Timestamp               *int64           `json:"timestamp"`               //YES
}
type PmMMarginOrderPostApi struct {
	client *PmMRestClient
	req    *PmMMarginOrderPostReq
}

func (api *PmMMarginOrderPostApi) Symbol(Symbol string) *PmMMarginOrderPostApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginOrderPostApi) Side(Side string) *PmMMarginOrderPostApi {
	api.req.Side = GetPointer(Side)
	return api
}
func (api *PmMMarginOrderPostApi) Type(Type string) *PmMMarginOrderPostApi {
	api.req.Type = GetPointer(Type)
	return api
}
func (api *PmMMarginOrderPostApi) Quantity(Quantity decimal.Decimal) *PmMMarginOrderPostApi {
	api.req.Quantity = GetPointer(Quantity)
	return api
}
func (api *PmMMarginOrderPostApi) QuoteOrderQty(QuoteOrderQty decimal.Decimal) *PmMMarginOrderPostApi {
	api.req.QuoteOrderQty = GetPointer(QuoteOrderQty)
	return api
}
func (api *PmMMarginOrderPostApi) Price(Price decimal.Decimal) *PmMMarginOrderPostApi {
	api.req.Price = GetPointer(Price)
	return api
}
func (api *PmMMarginOrderPostApi) StopPrice(StopPrice decimal.Decimal) *PmMMarginOrderPostApi {
	api.req.StopPrice = GetPointer(StopPrice)
	return api
}
func (api *PmMMarginOrderPostApi) NewClientOrderId(NewClientOrderId string) *PmMMarginOrderPostApi {
	api.req.NewClientOrderId = GetPointer(NewClientOrderId)
	return api
}
func (api *PmMMarginOrderPostApi) NewOrderRespType(NewOrderRespType string) *PmMMarginOrderPostApi {
	api.req.NewOrderRespType = GetPointer(NewOrderRespType)
	return api
}
func (api *PmMMarginOrderPostApi) IcebergQty(IcebergQty decimal.Decimal) *PmMMarginOrderPostApi {
	api.req.IcebergQty = GetPointer(IcebergQty)
	return api
}
func (api *PmMMarginOrderPostApi) SideEffectType(SideEffectType string) *PmMMarginOrderPostApi {
	api.req.SideEffectType = GetPointer(SideEffectType)
	return api
}
func (api *PmMMarginOrderPostApi) TimeInForce(TimeInForce string) *PmMMarginOrderPostApi {
	api.req.TimeInForce = GetPointer(TimeInForce)
	return api
}
func (api *PmMMarginOrderPostApi) SelfTradePreventionMode(SelfTradePreventionMode string) *PmMMarginOrderPostApi {
	api.req.SelfTradePreventionMode = GetPointer(SelfTradePreventionMode)
	return api
}
func (api *PmMMarginOrderPostApi) AutoRepayAtCancel(AutoRepayAtCancel bool) *PmMMarginOrderPostApi {
	api.req.AutoRepayAtCancel = GetPointer(AutoRepayAtCancel)
	return api
}
func (api *PmMMarginOrderPostApi) RecvWindow(RecvWindow int64) *PmMMarginOrderPostApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOrderPostApi) Timestamp(Timestamp int64) *PmMMarginOrderPostApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOrderDeleteReq struct {
	Symbol            *string `json:"symbol"`            //YES	交易对
	OrderId           *int64  `json:"orderId"`           //NO	订单ID
	OrigClientOrderId *int64  `json:"origClientOrderId"` //NO  必须发送 orderId 或 origClientOrderId 其中一个
	NewClientOrderId  *string `json:"newClientOrderId"`  //NO		用于唯一识别此撤销订单，默认自动生成。
	RecvWindow        *int64  `json:"recvWindow"`        //NO	赋值不能超过 60000
	Timestamp         *int64  `json:"timestamp"`         //YES
}
type PmMMarginOrderDeleteApi struct {
	client *PmMRestClient
	req    *PmMMarginOrderDeleteReq
}

func (api *PmMMarginOrderDeleteApi) Symbol(Symbol string) *PmMMarginOrderDeleteApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginOrderDeleteApi) OrderId(OrderId int64) *PmMMarginOrderDeleteApi {
	api.req.OrderId = GetPointer(OrderId)
	return api
}
func (api *PmMMarginOrderDeleteApi) OrigClientOrderId(OrigClientOrderId int64) *PmMMarginOrderDeleteApi {
	api.req.OrigClientOrderId = GetPointer(OrigClientOrderId)
	return api
}
func (api *PmMMarginOrderDeleteApi) NewClientOrderId(NewClientOrderId string) *PmMMarginOrderDeleteApi {
	api.req.NewClientOrderId = GetPointer(NewClientOrderId)
	return api
}
func (api *PmMMarginOrderDeleteApi) RecvWindow(RecvWindow int64) *PmMMarginOrderDeleteApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOrderDeleteApi) Timestamp(Timestamp int64) *PmMMarginOrderDeleteApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginAllOrdersReq struct {
	Symbol     *string `json:"symbol"`     //YES
	OrderId    *int64  `json:"orderId"`    //NO
	StartTime  *int64  `json:"startTime"`  //NO
	EndTime    *int64  `json:"endTime"`    //NO
	Limit      *int64  `json:"limit"`      //NO	默认 500;最大500.
	RecvWindow *int64  `json:"recvWindow"` //NO	赋值不能大于 60000
	Timestamp  *int64  `json:"timestamp"`  //YES
}
type PmMMarginAllOrdersApi struct {
	client *PmMRestClient
	req    *PmMMarginAllOrdersReq
}

func (api *PmMMarginAllOrdersApi) Symbol(Symbol string) *PmMMarginAllOrdersApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginAllOrdersApi) OrderId(OrderId int64) *PmMMarginAllOrdersApi {
	api.req.OrderId = GetPointer(OrderId)
	return api
}
func (api *PmMMarginAllOrdersApi) StartTime(StartTime int64) *PmMMarginAllOrdersApi {
	api.req.StartTime = GetPointer(StartTime)
	return api
}
func (api *PmMMarginAllOrdersApi) EndTime(EndTime int64) *PmMMarginAllOrdersApi {
	api.req.EndTime = GetPointer(EndTime)
	return api
}
func (api *PmMMarginAllOrdersApi) Limit(Limit int64) *PmMMarginAllOrdersApi {
	api.req.Limit = GetPointer(Limit)
	return api
}
func (api *PmMMarginAllOrdersApi) RecvWindow(RecvWindow int64) *PmMMarginAllOrdersApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginAllOrdersApi) Timestamp(Timestamp int64) *PmMMarginAllOrdersApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOpenOrdersReq struct {
	Symbol     *string `json:"symbol"`     //YES
	RecvWindow *int64  `json:"recvWindow"` //NO	赋值不能大于 60000
	Timestamp  *int64  `json:"timestamp"`  //YES
}
type PmMMarginOpenOrdersApi struct {
	client *PmMRestClient
	req    *PmMMarginOpenOrdersReq
}

func (api *PmMMarginOpenOrdersApi) Symbol(Symbol string) *PmMMarginOpenOrdersApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginOpenOrdersApi) RecvWindow(RecvWindow int64) *PmMMarginOpenOrdersApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOpenOrdersApi) Timestamp(Timestamp int64) *PmMMarginOpenOrdersApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOCOOrderGetReq struct {
	OrderListId       *int64  `json:"orderListId"`       //NO	orderListId 或 listClientOrderId 必须被提供
	OrigClientOrderId *string `json:"origClientOrderId"` //NO	orderListId 或 listClientOrderId 必须被提供
	RecvWindow        *int64  `json:"recvWindow"`        //NO	赋值不能大于 60000
	Timestamp         *int64  `json:"timestamp"`         //YES
}
type PmMMarginOCOOrderGetApi struct {
	client *PmMRestClient
	req    *PmMMarginOCOOrderGetReq
}

func (api *PmMMarginOCOOrderGetApi) OrderListId(OrderListId int64) *PmMMarginOCOOrderGetApi {
	api.req.OrderListId = GetPointer(OrderListId)
	return api
}
func (api *PmMMarginOCOOrderGetApi) OrigClientOrderId(OrigClientOrderId string) *PmMMarginOCOOrderGetApi {
	api.req.OrigClientOrderId = GetPointer(OrigClientOrderId)
	return api
}
func (api *PmMMarginOCOOrderGetApi) RecvWindow(RecvWindow int64) *PmMMarginOCOOrderGetApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOCOOrderGetApi) Timestamp(Timestamp int64) *PmMMarginOCOOrderGetApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOCOOrderPostReq struct {
	Symbol               *string          `json:"symbol"`               //YES	交易对
	ListClientOrderId    *string          `json:"listClientOrderId"`    //NO	整个 orderList 的唯一 ID
	Side                 *string          `json:"side"`                 //YES	详见枚举定义：订单方向
	Quantity             *decimal.Decimal `json:"quantity"`             //YES
	LimitClientOrderId   *string          `json:"limitClientOrderId"`   //NO	限价单的唯一 ID
	Price                *decimal.Decimal `json:"price"`                //YES
	LimitIcebergQty      *decimal.Decimal `json:"limitIcebergQty"`      //NO
	StopClientOrderId    *string          `json:"stopClientOrderId"`    //NO	止损/止损限价单的唯一 ID
	StopPrice            *decimal.Decimal `json:"stopPrice"`            //YES
	StopLimitPrice       *decimal.Decimal `json:"stopLimitPrice"`       //NO	如果提供，须配合提交stopLimitTimeInForce
	StopIcebergQty       *decimal.Decimal `json:"stopIcebergQty"`       //NO
	StopLimitTimeInForce *string          `json:"stopLimitTimeInForce"` //NO	有效值 GTC/FOK/IOC
	NewOrderRespType     *string          `json:"newOrderRespType"`     //NO	详见枚举定义：订单返回类型
	SideEffectType       *string          `json:"sideEffectType"`       //NO	NO_SIDE_EFFECT, MARGIN_BUY, AUTO_REPAY; 默认为 NO_SIDE_EFFECT
	RecvWindow           *int64           `json:"recvWindow"`           //NO	不能大于 60000
	Timestamp            *int64           `json:"timestamp"`            //YES
}
type PmMMarginOCOOrderPostApi struct {
	client *PmMRestClient
	req    *PmMMarginOCOOrderPostReq
}

func (api *PmMMarginOCOOrderPostApi) Symbol(Symbol string) *PmMMarginOCOOrderPostApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginOCOOrderPostApi) ListClientOrderId(ListClientOrderId string) *PmMMarginOCOOrderPostApi {
	api.req.ListClientOrderId = GetPointer(ListClientOrderId)
	return api
}
func (api *PmMMarginOCOOrderPostApi) Side(Side string) *PmMMarginOCOOrderPostApi {
	api.req.Side = GetPointer(Side)
	return api
}
func (api *PmMMarginOCOOrderPostApi) Quantity(Quantity decimal.Decimal) *PmMMarginOCOOrderPostApi {
	api.req.Quantity = GetPointer(Quantity)
	return api
}
func (api *PmMMarginOCOOrderPostApi) LimitClientOrderId(LimitClientOrderId string) *PmMMarginOCOOrderPostApi {
	api.req.LimitClientOrderId = GetPointer(LimitClientOrderId)
	return api
}
func (api *PmMMarginOCOOrderPostApi) Price(Price decimal.Decimal) *PmMMarginOCOOrderPostApi {
	api.req.Price = GetPointer(Price)
	return api
}
func (api *PmMMarginOCOOrderPostApi) LimitIcebergQty(LimitIcebergQty decimal.Decimal) *PmMMarginOCOOrderPostApi {
	api.req.LimitIcebergQty = GetPointer(LimitIcebergQty)
	return api
}
func (api *PmMMarginOCOOrderPostApi) StopClientOrderId(StopClientOrderId string) *PmMMarginOCOOrderPostApi {
	api.req.StopClientOrderId = GetPointer(StopClientOrderId)
	return api
}
func (api *PmMMarginOCOOrderPostApi) StopPrice(StopPrice decimal.Decimal) *PmMMarginOCOOrderPostApi {
	api.req.StopPrice = GetPointer(StopPrice)
	return api
}
func (api *PmMMarginOCOOrderPostApi) StopLimitPrice(StopLimitPrice decimal.Decimal) *PmMMarginOCOOrderPostApi {
	api.req.StopLimitPrice = GetPointer(StopLimitPrice)
	return api
}
func (api *PmMMarginOCOOrderPostApi) StopIcebergQty(StopIcebergQty decimal.Decimal) *PmMMarginOCOOrderPostApi {
	api.req.StopIcebergQty = GetPointer(StopIcebergQty)
	return api
}
func (api *PmMMarginOCOOrderPostApi) StopLimitTimeInForce(StopLimitTimeInForce string) *PmMMarginOCOOrderPostApi {
	api.req.StopLimitTimeInForce = GetPointer(StopLimitTimeInForce)
	return api
}
func (api *PmMMarginOCOOrderPostApi) NewOrderRespType(NewOrderRespType string) *PmMMarginOCOOrderPostApi {
	api.req.NewOrderRespType = GetPointer(NewOrderRespType)
	return api
}
func (api *PmMMarginOCOOrderPostApi) SideEffectType(SideEffectType string) *PmMMarginOCOOrderPostApi {
	api.req.SideEffectType = GetPointer(SideEffectType)
	return api
}
func (api *PmMMarginOCOOrderPostApi) RecvWindow(RecvWindow int64) *PmMMarginOCOOrderPostApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOCOOrderPostApi) Timestamp(Timestamp int64) *PmMMarginOCOOrderPostApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOCOOrderDeleteReq struct {
	Symbol            *string `json:"symbol"`            //YES
	OrderListId       *int64  `json:"orderListId"`       //NO	orderListId 或 listClientOrderId 必须被提供
	ListClientOrderId *string `json:"listClientOrderId"` //NO	orderListId 或 listClientOrderId 必须被提供
	NewClientOrderId  *string `json:"newClientOrderId"`  //NO	用户自定义的本次撤销操作的ID(注意不是被撤销的订单的自定义ID)。如无指定会自动赋值
	RecvWindow        *int64  `json:"recvWindow"`        //NO	赋值不能超过 60000
	Timestamp         *int64  `json:"timestamp"`         //YES
}
type PmMMarginOCOOrderDeleteApi struct {
	client *PmMRestClient
	req    *PmMMarginOCOOrderDeleteReq
}

func (api *PmMMarginOCOOrderDeleteApi) Symbol(Symbol string) *PmMMarginOCOOrderDeleteApi {
	api.req.Symbol = GetPointer(Symbol)
	return api
}
func (api *PmMMarginOCOOrderDeleteApi) OrderListId(OrderListId int64) *PmMMarginOCOOrderDeleteApi {
	api.req.OrderListId = GetPointer(OrderListId)
	return api
}
func (api *PmMMarginOCOOrderDeleteApi) ListClientOrderId(ListClientOrderId string) *PmMMarginOCOOrderDeleteApi {
	api.req.ListClientOrderId = GetPointer(ListClientOrderId)
	return api
}
func (api *PmMMarginOCOOrderDeleteApi) NewClientOrderId(NewClientOrderId string) *PmMMarginOCOOrderDeleteApi {
	api.req.NewClientOrderId = GetPointer(NewClientOrderId)
	return api
}
func (api *PmMMarginOCOOrderDeleteApi) RecvWindow(RecvWindow int64) *PmMMarginOCOOrderDeleteApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOCOOrderDeleteApi) Timestamp(Timestamp int64) *PmMMarginOCOOrderDeleteApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOCOAllOrdersReq struct {
	FromId     *int64 `json:"fromId"`     //NO	提供该项后, startTime 和 endTime 都不可提供
	StartTime  *int64 `json:"startTime"`  //NO
	EndTime    *int64 `json:"endTime"`    //NO
	Limit      *int64 `json:"limit"`      //NO	默认 500;最大500.
	RecvWindow *int64 `json:"recvWindow"` //NO	赋值不能大于 60000
	Timestamp  *int64 `json:"timestamp"`  //YES
}

type PmMMarginOCOAllOrdersApi struct {
	client *PmMRestClient
	req    *PmMMarginOCOAllOrdersReq
}

func (api *PmMMarginOCOAllOrdersApi) FromId(FromId int64) *PmMMarginOCOAllOrdersApi {
	api.req.FromId = GetPointer(FromId)
	return api
}

func (api *PmMMarginOCOAllOrdersApi) StartTime(StartTime int64) *PmMMarginOCOAllOrdersApi {
	api.req.StartTime = GetPointer(StartTime)
	return api
}
func (api *PmMMarginOCOAllOrdersApi) EndTime(EndTime int64) *PmMMarginOCOAllOrdersApi {
	api.req.EndTime = GetPointer(EndTime)
	return api
}
func (api *PmMMarginOCOAllOrdersApi) Limit(Limit int64) *PmMMarginOCOAllOrdersApi {
	api.req.Limit = GetPointer(Limit)
	return api
}
func (api *PmMMarginOCOAllOrdersApi) RecvWindow(RecvWindow int64) *PmMMarginOCOAllOrdersApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOCOAllOrdersApi) Timestamp(Timestamp int64) *PmMMarginOCOAllOrdersApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}

type PmMMarginOCOOpenOrdersReq struct {
	RecvWindow *int64 `json:"recvWindow"` //NO	赋值不能大于 60000
	Timestamp  *int64 `json:"timestamp"`  //YES
}
type PmMMarginOCOOpenOrdersApi struct {
	client *PmMRestClient
	req    *PmMMarginOCOOpenOrdersReq
}

func (api *PmMMarginOCOOpenOrdersApi) RecvWindow(RecvWindow int64) *PmMMarginOCOOpenOrdersApi {
	api.req.RecvWindow = GetPointer(RecvWindow)
	return api
}
func (api *PmMMarginOCOOpenOrdersApi) Timestamp(Timestamp int64) *PmMMarginOCOOpenOrdersApi {
	api.req.Timestamp = GetPointer(Timestamp)
	return api
}
